apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backendRB
  name: BE_deploy_RB
spec:
  selector:
    matchLabels:
      app: resumebuilder
  template:
    metadata:
      labels:
        app: resumebuilder
    spec:
      containers:
      - name: resumebuilder
        image: ravikishans/resumebuilder:backend
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_URI
        - name: PORT
          value: "4292"
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 4292
