apiVersion: v1
kind: Service
metadata:
  namespace: databaseRB
  name: DB_service_RB
spec:
  selector:
    app: resumebuilder
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
