apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-rb
  namespace: {{ .Values.frontend.namespace }}
  labels:
    app: {{ .Release.Name }}-fe-rb
data:
  REACT_APP_BACKEND_URL: {{ .Values.frontend.data.REACT_APP_BACKEND_URL }}