apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  namespace: {{ .Values.database.namespace }}
spec:
  capacity:
    storage: {{ .Values.database.pvc.storage }}  
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data