apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Values.database.namespace }}
spec:
  resources:
    requests:
      storage: {{ .Values.database.pvc.storage }}
  # volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce