apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-be-secret
  namespace: {{ .Values.backend.namespace }}
data:
  MONGO_URI: {{ .Values.backend.env.MONGO_URL | b64enc }}
# mongodb://ravikishan:Cluster0@cluster0.y9zohpu.mongodb.net:27017/
type: Opaque