apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: databaserb
  name: rb-pv
spec:
  capacity:
    storage: 3Gi
  # volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Recycle
  # storageClassName: slow
  # mountOptions:
  # - hard
  # - nfsvers=4.1
  # nfs:
  # path: /tmp
  # server: 172.17.0.2
  hostPath:
    path: /mnt/data
