apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: databaserb
  name: rb-pvc
spec:
  resources:
    requests:
      storage: 3Gi
  # volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce

