apiVersion: v1
kind: Secret
metadata:
  namespace: backendrb
  name: backend-secret
type: Opaque
data:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9yYXZpa2lzaGFuOkNsdXN0ZXIwQGNsdXN0ZXIwLnk5em9ocHUubW9uZ29kYi5uZXQvcmVzdW1lYWk="
# mongodb+srv://ravikishan:Cluster0@cluster0.y9zohpu.mongodb.net/resumeai"
