apiVersion: v1
kind: Service
metadata:
  namespace: backendrb
  name: be-service-rb
spec:
  type: LoadBalancer
  selector:
    app: resumebuilder
  ports:
  - port: 4292
    targetPort: 4292



---
apiVersion: v1
kind: Service
metadata:
  namespace: frontendrb
  name: fe-service-rb
spec:
  type: LoadBalancer
  selector:
    app: resumebuilder
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: databaserb
  name: db-service-rb
spec:
  selector:
    app: resumebuilder
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: LoadBalancer
